# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: 'docker-login'

steps:
- task: Docker@2
  displayName: 'Docker build and push to registry'
  inputs:
    containerRegistry: 'Mike Wild Container Registry'
    repository: docker-test
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)'

- task: AzureCLI@2
  displayName: 'Docker run'
  inputs:
    azureSubscription: 'ARM Subscription'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 
      'az container create --resource-group docker -name docker-test --location uksouth --image mikewilddocker.azurecr.io/docker-test:$(Build.BuildId) --dns-name-label mikewilddocker-dns --ports 80 --registry-username $(username) --registry-password $(password)'
