# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Docker'
  inputs:
    containerRegistry: 'Mike Wild Container Registry'
    repository: docker-test
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)'
